version: 1

project:
  root: .
  build_config: lzc-build.yml
  package_file: package.yml
  output: .lazycat-build/hatchdoor.lpk
  target_arch: amd64

update:
  strategy: publish
  allow_downgrade: false
  version_source:
    type: image
    image: hatchdoor

build:
  run_buildscript: false

images:
  - id: hatchdoor
    target: service
    service: hatchdoor
    source: docker.io/battermanz/hatchdoor
    channel: stable
    sort: semver
    tag_regex: '^v?[0-9]+\.[0-9]+\.[0-9]+$'
    delivery:
      mode: mirror
      image_template: docker.1ms.run/battermanz/hatchdoor:{tag}
      require_digest_match: true

stores:
  official:
    enabled: false
  private:
    enabled: true
    skip_if_version_exists: true
    name: Hatchdoor
    summary: 由 GitHub Actions 自动发布